version: '3.9'
services:

  redis:
    restart: always
    image: redis
    expose:
      - 6379

  db_hans3d:
    restart: always
    platform: linux/amd64
    container_name: db_hans3d
    image: postgres:12-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - data_hans3d_db:/var/lib/postgresql/db_hans3d

  db_user:
    restart: always
    platform: linux/amd64
    container_name: db_user
    image: postgres:12-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=db_user
    volumes:
      - data_user:/var/lib/postgresql/ db_user

  users:
    restart: always
    build: ./backend/users
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    expose:
      - 8000
    environment:
      - AUTH_URL=postgresql://postgres:1234567890@db_user:5432/db_user
    depends_on:
      - db_user

  hans3d:
    restart: always
    build: ./backend/hans3d
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8003
    ports:
      - 8003:8003
    expose:
      - 8003
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@db_hans3d:5432/db_hans3d
    depends_on:
      - db_hans3d

  auth:
    restart: always
    build: ./backend/auth
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002
    expose:
      - 8002
    environment:
      - URL_USERS=http://users:8000
      - URL_REDIS=redis
      - URL_HANS3D=http://hans3d:8003
    depends_on:
      - redis
      - users
      - hans3d

  nginx:
    restart: always
    platform: linux/amd64
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  data_hans3d_db:
  data_user:


