


SECRET_KEY_ACCESS_TOKEN = "3DmedVN23dbfghjkbdsjkgrsngsdfniwehgdsnfgkjdsnfdjksfdsf"
SECRET_KEY_REFRESH_TOKEN = "3DmedVN23768686dsfdsfdasfdsfdsdsfdsfdsfdsfdsfdsfewfewfdbfbfdgds"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
ACCESS_TOKEN_EXPIRE_DAYS = 7
ACCESS_TOKEN_EXPIRE_YEARS = 1
REFRESH_TOKEN_EXPIRE_MINUTES = 120
REFRESH_TOKEN_EXPIRE_DAYS = 7
REFRESH_TOKEN_EXPIRE_YEARS = 1

#CHOICE: MINUTES, DAYS, YEARS, NONE = NEVER EXPIRE
ACCESS_TOKEN_EXPIRE_TYPE = "MINUTES"
REFRESH_TOKEN_EXPIRE_TYPE = "MINUTES"